# Generated by Django 4.1.7 on 2023-04-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumno', models.CharField(max_length=30)),
                ('apellido_alumno', models.CharField(max_length=30)),
                ('fecha_entrega', models.DateField()),
                ('nota', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
